name: Build and deploy to Cycle.io

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cycle.io pipeline
        run: |
          curl -f https://api.cycle.io/v1/pipelines/67619cbd0cefa3229efcbe00/trigger \
            -H "Content-Type: application/json" \
            -d "{\"secret\": \"${{ secrets.CYCLE_TRIGGER_KEY }}\", \"variables\": {\"version\": \"${{ github.sha | slice(0, 7) }}\"}}" \
            -X POST
